name: TrueRPCMini
options:
  bundleIdPrefix: com.truewebber
  generateEmptyDirectories: true
schemes:
  TrueRPCMini:
    build:
      targets:
        TrueRPCMini: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TrueRPCMiniTests
targets:
  TrueRPCMini:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - Sources
      - path: Resources
        type: folder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.truewebber.TrueRPCMini
    dependencies:
      - package: SwiftProtoReflect
      - package: SwiftProtoParser
      - package: GRPCCore
      - package: GRPCNIOTransportHTTP2
  TrueRPCMiniTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Tests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TrueRPCMini
packages:
  SwiftProtoReflect:
    url: https://github.com/truewebber/swift-protoreflect
    from: 4.2.0
  SwiftProtoParser:
    url: https://github.com/truewebber/swift-protoparser
    from: 0.3.0
  GRPCCore:
    url: https://github.com/grpc/grpc-swift-2.git
    from: 2.0.0
  GRPCNIOTransportHTTP2:
    url: https://github.com/grpc/grpc-swift-nio-transport.git
    from: 2.0.0
