name: TrueRPCMini
options:
  bundleIdPrefix: com.truewebber
  generateEmptyDirectories: true
schemes:
  TrueRPCMini:
    build:
      targets:
        TrueRPCMini: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TrueRPCMiniTests
targets:
  TrueRPCMini:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - Sources
      - path: Resources
        type: folder
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.truewebber.TrueRPCMini
        MARKETING_VERSION: "0.0.1"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "TrueRPC-mini"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        DEVELOPMENT_TEAM: "57UWRPUUGM"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          ENABLE_HARDENED_RUNTIME: YES
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Apple Development"
          ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: SwiftProtoReflect
      - package: SwiftProtoParser
      - package: GRPCCore
      - package: GRPCNIOTransportHTTP2
      - package: Amplitude-Swift
        product: AmplitudeSwift
  TrueRPCMiniTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Tests]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TrueRPCMini
packages:
  SwiftProtoReflect:
    url: https://github.com/truewebber/swift-protoreflect
    from: 4.2.0
  SwiftProtoParser:
    url: https://github.com/truewebber/swift-protoparser
    from: 0.3.0
  GRPCCore:
    url: https://github.com/grpc/grpc-swift-2.git
    from: 2.0.0
  GRPCNIOTransportHTTP2:
    url: https://github.com/grpc/grpc-swift-nio-transport.git
    from: 2.0.0
  Amplitude-Swift:
    url: https://github.com/amplitude/Amplitude-Swift
    from: "1.0"
